[package]
name = "ness-desktop"
version = "0.0.0"
edition = "2021"
publish = false

[features]
default = ["debug-views", "log", "discord-presence"]

debug-views = ["bitflags", "ness-core/disasm"]
log = ["slog", "slog-term", "slog-async", "ness-core/log"]
discord-presence = ["discord-rpc"]

compile-shaders = ["shaderc"]

[dependencies]
ness-core = { path = "../../core" }
bitflags = { version = "1.3", optional = true }
fxhash = "0.2"
winit = { version = "0.26", features = ["serde"] }
wgpu = { version = "0.12", features = ["spirv"] }
futures-executor = "0.3"
imgui = "0.8"
imgui-winit-support = { version = "0.8", features = ["winit-26"] }
crossbeam-channel = "0.5"
slog = { version = "2.7", optional = true }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
slog-term = { version = "2.8", optional = true }
slog-async = { version = "2.6", optional = true }
rfd = "0.6"
home = "0.5"
sha2 = "0.10"
parking_lot = "0.11"
cpal = "0.13"
discord-rpc = { git = "https://github.com/kelpsyberry/discord-rpc", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24" # TODO: Remove when https://github.com/rust-windowing/winit/issues/2022 is closed

[build-dependencies]
shaderc = { version = "0.7", optional = true }
