name: Build release binaries

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  DEBUG_FEATURES: log,debug-views

jobs:
  build:
    name: Build release binaries
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact: Windows
            artifact-extension: .exe
          - os: ubuntu-latest
            artifact: Linux
          - os: macos-latest
            artifact: macOS
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: clippy
    - name: Install GTK
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install libgtk-3-dev
    - name: Build release binary (no debugging features)
      run: cargo build --release --verbose --no-default-features
    - name: Upload release binary (no debugging features)
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.artifact }}
        path: target/release/ness-desktop${{ matrix.artifact-extension }}
    - name: Build release binary (debugging features)
      run: cargo build --release --verbose --features=${{ env.DEBUG_FEATURES }}
    - name: Upload release binary (debugging features)
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.artifact }}-debug
        path: target/release/ness-desktop${{ matrix.artifact-extension }}
